In [16]:
import pandas as pd
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.linear_model import LinearRegression
import random

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/MIDASpy/midas_base.py:700: SyntaxWarning: invalid escape sequence '\c'
  """

tfVersionError: midas v1.0 is currently only compatible with TensorFlow 1.X

In [2]:
# Set random seed for reproducibility
np.random.seed(2026)

n_rows = 20
# Create original dataframe
df_example = pd.DataFrame({
    'A': np.arange(1, n_rows + 1) * 2,
    'B': 5 + np.arange(1, n_rows + 1) * 2 + 10 * np.random.normal(size=n_rows),
    'C': 2 + np.sqrt(np.arange(1, n_rows + 1)) + np.random.normal(size=n_rows)
})

# Create copy with missing values
df_example_miss = df_example.copy()
df_example_miss.loc[[1, 4, 12], 'A'] = np.nan  # R indices 2,5
df_example_miss.loc[[0, 1, 7, 19], 'B'] = np.nan  # R indices 1,2,8
df_example_miss.loc[[8, 9, 10, 13, 14, 15, 16, 17], 'C'] = np.nan  # R indices 9,10
df_example_miss

       A          B         C
0    2.0        NaN  3.359768
1    NaN        NaN  4.160385
2    6.0  14.115707  1.007192
3    8.0  12.867651  5.675379
4    NaN  29.497077  4.292301
5   12.0  19.981527  2.750244
6   14.0  10.701040  4.284394
7   16.0        NaN  7.558177
8   18.0  29.134378       NaN
9   20.0  21.824029       NaN
10  22.0  26.260033       NaN
11  24.0  22.913691  5.849474
12   NaN  11.001270  4.985185
13  28.0  42.082407       NaN
14  30.0  39.829799       NaN
15  32.0  39.218785       NaN
16  34.0  45.640292       NaN
17  36.0  28.541932       NaN
18  38.0  62.688791  6.505253
19  40.0        NaN  6.038750

In [3]:
imp = IterativeImputer(random_state=42, max_iter=10, n_nearest_features=None)
df_example_imp_single = pd.DataFrame(
    imp.fit_transform(df_example_miss),
    columns=df_example_miss.columns
)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/impute/_iterative.py:895: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [4]:
df_example_imp_single

            A          B         C
0    2.000000   4.520278  3.359768
1   20.456460  26.476873  4.160385
2    6.000000  14.115707  1.007192
3    8.000000  12.867651  5.675379
4   22.423881  29.497077  4.292301
5   12.000000  19.981527  2.750244
6   14.000000  10.701040  4.284394
7   16.000000  20.889377  7.558177
8   18.000000  29.134378  4.814166
9   20.000000  21.824029  4.730386
10  22.000000  26.260033  4.873288
11  24.000000  22.913691  5.849474
12  10.943481  11.001270  4.985185
13  28.000000  42.082407  5.350515
14  30.000000  39.829799  5.364339
15  32.000000  39.218785  5.409844
16  34.000000  45.640292  5.591061
17  36.000000  28.541932  5.318393
18  38.000000  62.688791  6.505253
19  40.000000  49.644656  6.038750

In [5]:
lr = LinearRegression()
imp = IterativeImputer(estimator=lr, verbose=2, max_iter=5, tol=1e-10, imputation_order='roman')
ImputedData=imp.fit_transform(df_example_miss)

[IterativeImputer] Completing matrix with shape (20, 3)
[IterativeImputer] Ending imputation round 1/5, elapsed time 0.00
[IterativeImputer] Change: 25.035563624989635, scaled tolerance: 6.268879071653625e-09
[IterativeImputer] Ending imputation round 2/5, elapsed time 0.00
[IterativeImputer] Change: 10.608866003681783, scaled tolerance: 6.268879071653625e-09
[IterativeImputer] Ending imputation round 3/5, elapsed time 0.00
[IterativeImputer] Change: 2.6077812191058953, scaled tolerance: 6.268879071653625e-09
[IterativeImputer] Ending imputation round 4/5, elapsed time 0.01
[IterativeImputer] Change: 0.644972169598546, scaled tolerance: 6.268879071653625e-09
[IterativeImputer] Ending imputation round 5/5, elapsed time 0.01
[IterativeImputer] Change: 0.37304547731739746, scaled tolerance: 6.268879071653625e-09

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/impute/_iterative.py:895: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [6]:
Imputed_data = pd.DataFrame(ImputedData)
Imputed_data

            0          1         2
0    2.000000  -0.620332  3.359768
1   17.971741  25.607542  4.160385
2    6.000000  14.115707  1.007192
3    8.000000  12.867651  5.675379
4   20.087299  29.497077  4.292301
5   12.000000  19.981527  2.750244
6   14.000000  10.701040  4.284394
7   16.000000   6.932892  7.558177
8   18.000000  29.134378  3.982857
9   20.000000  21.824029  5.563885
10  22.000000  26.260033  5.561438
11  24.000000  22.913691  5.849474
12  12.856581  11.001270  4.985185
13  28.000000  42.082407  5.215147
14  30.000000  39.829799  6.114363
15  32.000000  39.218785  6.792282
16  34.000000  45.640292  6.522179
17  36.000000  28.541932  9.422684
18  38.000000  62.688791  6.505253
19  40.000000  58.363383  6.038750

In [7]:
df_example.mean()

A    21.000000
B    25.045220
C     5.071751
dtype: float64

In [8]:
df_example_miss.mean()

A    22.352941
B    28.518651
C     4.705542
dtype: float64

In [9]:
Imputed_data.mean()

0    21.545781
1    27.329095
2     5.282067
dtype: float64