In [1]:
import pandas as pd
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.linear_model import LinearRegression
import random

In [2]:
# Set random seed for reproducibility
np.random.seed(42)

n_rows = 20
# Create original dataframe
df_example = pd.DataFrame({
    'A': np.arange(1, n_rows + 1) * 2,
    'B': 5 + np.arange(1, n_rows + 1) * 2 + 10 * np.random.normal(size=n_rows),
    'C': 2 + np.sqrt(np.arange(1, n_rows + 1)) + np.random.normal(size=n_rows)
})

# Create copy with missing values
df_example_miss = df_example.copy()
df_example_miss.loc[[1, 4, 12], 'A'] = np.nan  # R indices 2,5
df_example_miss.loc[[0, 1, 7, 19], 'B'] = np.nan  # R indices 1,2,8
df_example_miss.loc[[8, 9, 10, 13, 14, 15, 16, 17], 'C'] = np.nan  # R indices 9,10
df_example_miss

       A          B         C
0    2.0        NaN  4.465649
1    NaN        NaN  3.188437
2    6.0  17.476885  3.799579
3    8.0  28.230299  2.575252
4    NaN  12.658466  3.691685
5   12.0  14.658630  4.560412
6   14.0  34.792128  3.494758
7   16.0        NaN  5.204125
8   18.0  18.305256       NaN
9   20.0  30.425600       NaN
10  22.0  22.365823       NaN
11  24.0  24.342702  7.316380
12   NaN  33.419623  5.592054
13  28.0  13.867198       NaN
14  30.0  17.750822       NaN
15  32.0  31.377125       NaN
16  34.0  28.871689       NaN
17  36.0  44.142473       NaN
18  38.0  33.919759  5.030713
19  40.0        NaN  6.668997

In [3]:
imp = IterativeImputer(random_state=42, max_iter=10, n_nearest_features=None)
df_example_imp_single = pd.DataFrame(
    imp.fit_transform(df_example_miss),
    columns=df_example_miss.columns
)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/impute/_iterative.py:895: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [4]:
df_example_imp_single

            A          B         C
0    2.000000  11.308202  4.465649
1    7.938353  23.651340  3.188437
2    6.000000  17.476885  3.799579
3    8.000000  28.230299  2.575252
4    1.927999  12.658466  3.691685
5   12.000000  14.658630  4.560412
6   14.000000  34.792128  3.494758
7   16.000000  19.375253  5.204125
8   18.000000  18.305256  5.324366
9   20.000000  30.425600  4.346735
10  22.000000  22.365823  5.392295
11  24.000000  24.342702  7.316380
12  32.143211  33.419623  5.592054
13  28.000000  13.867198  6.956878
14  30.000000  17.750822  6.805033
15  32.000000  31.377125  5.676420
16  34.000000  28.871689  6.165120
17  36.000000  44.142473  4.871637
18  38.000000  33.919759  5.030713
19  40.000000  32.088718  6.668997

In [5]:
lr = LinearRegression()
imp = IterativeImputer(estimator=lr, verbose=2, max_iter=5, tol=1e-10, imputation_order='roman')
ImputedData=imp.fit_transform(df_example_miss)

[IterativeImputer] Completing matrix with shape (20, 3)
[IterativeImputer] Ending imputation round 1/5, elapsed time 0.01
[IterativeImputer] Change: 13.051326494599557, scaled tolerance: 4.414247332595274e-09
[IterativeImputer] Ending imputation round 2/5, elapsed time 0.01
[IterativeImputer] Change: 8.117869896232882, scaled tolerance: 4.414247332595274e-09
[IterativeImputer] Ending imputation round 3/5, elapsed time 0.01
[IterativeImputer] Change: 0.833902429665816, scaled tolerance: 4.414247332595274e-09
[IterativeImputer] Ending imputation round 4/5, elapsed time 0.02
[IterativeImputer] Change: 0.6558870530186631, scaled tolerance: 4.414247332595274e-09
[IterativeImputer] Ending imputation round 5/5, elapsed time 0.02
[IterativeImputer] Change: 0.5541145150858, scaled tolerance: 4.414247332595274e-09

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/impute/_iterative.py:895: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [6]:
Imputed_data = pd.DataFrame(ImputedData)
Imputed_data

            0          1         2
0    2.000000  11.350182  4.465649
1    8.240235  24.466321  3.188437
2    6.000000  17.476885  3.799579
3    8.000000  28.230299  2.575252
4    0.937879  12.658466  3.691685
5   12.000000  14.658630  4.560412
6   14.000000  34.792128  3.494758
7   16.000000  19.525065  5.204125
8   18.000000  18.305256  5.469321
9   20.000000  30.425600  4.266226
10  22.000000  22.365823  5.499482
11  24.000000  24.342702  7.316380
12  32.299766  33.419623  5.592054
13  28.000000  13.867198  7.306115
14  30.000000  17.750822  7.097441
15  32.000000  31.377125  5.712531
16  34.000000  28.871689  6.275210
17  36.000000  44.142473  4.691762
18  38.000000  33.919759  5.030713
19  40.000000  32.366218  6.668997

In [7]:
df_example.mean()

A    21.000000
B    24.287014
C     4.817324
dtype: float64

In [8]:
df_example_miss.mean()

A    22.352941
B    25.412780
C     4.632337
dtype: float64

In [9]:
Imputed_data.mean()

0    21.073894
1    24.715613
2     5.095307
dtype: float64